### PR TITLE
Support serial device inputs to terminal window

### PR DESCRIPTION
**Pull request by Detegr**
When debugging an embedded device, the device often uses a serial port for printing debug messages. This commit allows the ugdb tui terminal to receive input from a serial console instead of the stdout of the program being debugged.

I'm using the gdb console to print out error messages if the pty cannot be opened, and the terminal window if the pty is available. I found out that errors from the terminal window are much easier to spot (if giving a wrong device for example). If the connection to the serial port is lost, the implementation is not able to recover. I thought this is not a big deal, as the debugging session is probably gone too if that happens.

This brings in a dependency of `serial` crate. It is not 100% necessary, but makes the serial configuration easier to read, so I figured it might be okay to use that instead of `nix::sys::termios` directly.

### CODE REVIEW

**Comment by Detegr** [comment]
I tested out quickly that this seems to work okay. I'll give it a good battle test tomorrow (maybe with a colleague) while I'm planning on debugging a real world work project of mine with `ugdb`.

**Review by dancek — APPROVED** [review]
LGTM and I'd have use for this 👍

**Comment by ftilde** [comment]
All in all I would say your patch looks fine and I'm not opposed to 
merging it. I have a question about the usage and potential implied 
further changes though, as it has been a while since I last worked with 
embedded devices:

It looks like this patch simply implements a "one way" serial client 
that happens to run inside ugdb. An alternative would probably be to use 
minicom or nanocom for the same job. The advantage here is simply the 
convenience to not have to open another window. Is that correct?

Don't get me wrong: I see a benefit in something like this since its 
basically the same story for the separate tty/terminal emulator that you 
also use for the output here. One difference is that this happens 
automatically for the tty case. Which brings me to the question: I'm 
guessing that you use gdb with a serial remote target for debugging as 
well then. Is that the same serial port that you would supply as 
`serial_terminal_input` here or are these two different? In the former 
case maybe it would make sense to merge this setting with an option that 
connects to the serial remote target as well.

On 02.09.2021 10:57, Antti Keränen wrote:
>When debugging an embedded device, the device often uses a serial portfor printing debug messages. This commit allows the ugdb tui terminal toreceive input from a serial console instead of the stdout of the programbeing debugged.
>
>I&#39;m using the gdb console to print out error messages if the pty cannot be opened, and the terminal window if the pty is available. I found out that errors from the terminal window are much easier to spot (if giving a wrong device for example). If the connection to the serial port is lost, the implementation is not able to recover. I thought this is not a big deal, as the debugging session is probably gone too if that happens.
>
>This brings in a dependency of `serial` crate. It is not 100% necessary, but makes the serial configuration easier to read, so I figured it might be okay to use that instead of `nix::sys::termios` directly.
>You can view, comment on, or merge this pull request online at:
>
>  https://github.com/ftilde/ugdb/pull/21
>
>-- Commit Summary --
>
>  * Support serial device inputs to terminal window
>
>-- File Changes --
>
>    M Cargo.lock (63)
>    M Cargo.toml (1)
>    M src/main.rs (64)
>    A src/serial.rs (107)
>
>-- Patch Links --
>
>https://github.com/ftilde/ugdb/pull/21.patch
>https://github.com/ftilde/ugdb/pull/21.diff
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/ftilde/ugdb/pull/21

-- 
Dominik Drees

Department of Computer Science
Westfaelische Wilhelms-Universitaet Muenster

email: ***@***.***
web: https://www.wwu.de/PRIA/personen/drees.shtml
phone: +49 251 83 - 38448

**Comment by Detegr** [comment]
Yes, this just implements a read-only serial client, advantage being that you don't need to open another window. Now that you mention it, it should probably be a read/write one, like the way the terminal works for normal binaries. This makes me to think if the better solution would be to allow running a separate program in a ugdb window, like picocom...

For the latter question: I don't think this works in a situation that the target is a serial remote one. I designed this to be used in a situation where you have a JTAG (or similar) connection for debugging (via openocd for example) and a separate serial port for printing out/reading in messages.

What do you think would be the best option: allow running external programs within ugdb's terminal window (this could get hairy because of possible conflicting keybindings between the programs), implementing this with write direction too, or just making the decision of not implementing anything because the only benefit is the convenience of not having to have a separate window open?

**Comment by ftilde** [comment]
On 05.09.2021 02:39, Antti Keränen wrote:
>For the latter question: I don't think this works in a situation that the target is a serial remote one. I designed this to be used in a situation where you have a JTAG (or similar) connection for debugging (via openocd for example) and a separate serial port for printing out/reading in messages.
I see. I was already wondering how multiplexing of the connection that 
would also be shared with gdb would work. That makes sense.

>What do you think would be the best option: allow running external programs within ugdb's terminal window (this could get hairy because of possible conflicting keybindings between the programs), implementing this with write direction too, or just making the decision of not implementing anything because the only benefit is the convenience of not having to have a separate window open?
Hm. I don't think allowing additional programs in ugdbs terminal window 
makes sense. That would make ugdb basically a poor man's terminal 
multiplexer. This "general" solution would be hardly more convenient 
than running ugdb and picocom next to each other in tmux or something 
(in terms of the amount of configuration needed).

For the question if it's a good idea to still allow ugdb to also be a 
serial client I would want to rely on your (and possibly your 
colleague's) judgement since I *personally* don't see a use in it 
because I don't work with embedded systems at the moment. If you can 
definitely say that it's useful for you, I'm fine with merging the 
functionality (possibly after adding the write-channel). Maybe you can 
compare the built-in version with running ugdb next to picocom in tmux 
or screen and report back?
Since the terminal emulator is of no use in your use case you can also 
hide it by choosing a different layout: For example try running ugdb as 
`ugdb --layout s-c-e`.

**Comment by Detegr** [comment]
After pondering this for a while I think embedding the serial communication in ugdb is not worth the complexity it adds. Running a separate window with picocom or similar and running ugdb with a layout that does not have a terminal window is actually good and usable solution. I'm closing this PR, thank you for the discussion.

**Pull request closed without merging**
